name = "dcvaas-ui"
main = "workers/spa.ts"
compatibility_date = "2024-09-23"

# This uploads your "dist" folder (the React build) to Cloudflare
[assets]
directory = "./dist"
binding = "ASSETS"

[[routes]]
pattern = "cert.pcnaid.com"
zone_name = "pcnaid.com"
